import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const pptxgen = require("pptxgenjs");
import { AlignmentType, Document, Footer, HeadingLevel, Packer, PageBreak, Paragraph, ShadingType, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
const slug = "A01-o-incidente-que-parou-a-linha";
const slideDir = resolve(root, "slides", slug, "fonte");
const activityDir = resolve(root, "atividades", slug, "fonte");
await Promise.all([mkdir(slideDir, { recursive: true }), mkdir(activityDir, { recursive: true })]);

const C = { navy:"12304A", blue:"0B65C2", cyan:"087F7A", amber:"B75D00", red:"B42318", paper:"F4F7FA", ink:"172B4D", white:"FFFFFF", grey:"4B5E71", line:"C9D4DF", pale:"E7F0F8" };
const pptx = new pptxgen();
pptx.layout = "LAYOUT_WIDE"; pptx.author = "Curso de Segurança Digital"; pptx.title = "A01 — O incidente que parou a linha"; pptx.lang = "pt-BR";
pptx.theme = { headFontFace:"Arial", bodyFontFace:"Arial", lang:"pt-BR" };
const footer=(s,src="NIST SP 800-82 Rev. 3")=>{s.addShape(pptx.ShapeType.line,{x:.6,y:7.08,w:12.05,h:0,line:{color:C.line,width:1}});s.addText("A01  •  Segurança Digital",{x:.65,y:7.14,w:4,h:.2,fontFace:"Arial",fontSize:10,color:C.grey,margin:0});s.addText(src,{x:7.1,y:7.14,w:5.55,h:.2,fontFace:"Arial",fontSize:9,color:C.grey,align:"right",margin:0});};
const head=(s,k,t,sub="")=>{s.addText(k.toUpperCase(),{x:.7,y:.42,w:4.8,h:.28,fontSize:13,bold:true,color:C.cyan,charSpacing:1,margin:0});s.addText(t,{x:.7,y:.84,w:11.9,h:.72,fontSize:30,bold:true,color:C.navy,margin:0,fit:"shrink"});if(sub)s.addText(sub,{x:.72,y:1.65,w:11.4,h:.44,fontSize:17,color:C.grey,margin:0,fit:"shrink"});};
const notes=(s,t)=>s.addNotes(t);

{
 const s=pptx.addSlide();s.background={color:C.navy};s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:.22,h:7.5,fill:{color:C.cyan},line:{color:C.cyan}});
 s.addText("A01  •  FUNDAMENTOS E RISCO",{x:.8,y:.72,w:5.5,h:.32,fontSize:14,bold:true,color:"7DE0D8",charSpacing:1.2,margin:0});
 s.addText("O incidente que\nparou a linha",{x:.8,y:1.45,w:7.1,h:1.55,fontSize:40,bold:true,color:C.white,margin:0,breakLine:false});
 s.addText("Às 09:17, produção cai a zero. A rede continua respondendo. O que você pode afirmar?",{x:.82,y:3.35,w:7.3,h:1.05,fontSize:22,color:"E6EEF5",margin:0});
 s.addShape(pptx.ShapeType.roundRect,{x:9.1,y:1.4,w:3.1,h:3.15,fill:{color:"1B4666"},line:{color:"7DE0D8",width:2}});s.addText("09:17\n0 un/min",{x:9.45,y:2.18,w:2.4,h:1.15,fontSize:29,bold:true,color:C.white,align:"center",valign:"mid",margin:0});
 s.addText("2 × 52 min  •  investigação em duplas",{x:.82,y:6.55,w:5.2,h:.3,fontSize:14,color:"C7D6E4",margin:0});
 notes(s,"Mostre a evidência por 30 segundos. Peça duas observações sem interpretação. Não confirme a causa.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Missão","Separar fato, hipótese e consequência","Você integra uma equipe chamada para apoiar a sala de controle.");
 const cards=[["FATO","A esteira parou às 09:17.",C.blue],["RESTRIÇÃO","Não interromper o controlador.",C.amber],["ENTREGA","Linha do tempo + hipótese justificada.",C.cyan]];
 cards.forEach(([h,b,c],i)=>{const x=.75+i*4.12;s.addShape(pptx.ShapeType.roundRect,{x,y:2.45,w:3.72,h:2.55,fill:{color:C.white},line:{color:c,width:2}});s.addText(h,{x:x+.28,y:2.78,w:3.1,h:.35,fontSize:15,bold:true,color:c,margin:0});s.addText(b,{x:x+.28,y:3.35,w:3.12,h:1.05,fontSize:21,bold:true,color:C.navy,margin:0,fit:"shrink"});});footer(s);notes(s,"Forme duplas: uma pessoa lê evidências; outra desafia inferências. Troque os papéis no segundo bloco.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Previsão","Qual hipótese você testaria primeiro?","Escolha antes de ver o conjunto completo de evidências.");
 const opts=[["A","Falha mecânica local"],["B","Ação indevida no supervisório"],["C","Perda de comunicação OT"]];opts.forEach(([l,t],i)=>{const y=2.35+i*1.1;s.addShape(pptx.ShapeType.ellipse,{x:1,y,w:.62,h:.62,fill:{color:[C.blue,C.cyan,C.amber][i]},line:{color:C.white,transparency:100}});s.addText(l,{x:1,y:y+.12,w:.62,h:.25,fontSize:17,bold:true,color:C.white,align:"center",margin:0});s.addText(t,{x:1.9,y:y+.06,w:7.4,h:.45,fontSize:22,bold:true,color:C.navy,margin:0});});
 s.addShape(pptx.ShapeType.roundRect,{x:9.55,y:2.4,w:2.75,h:3.05,fill:{color:C.pale},line:{color:C.line}});s.addText("REGISTRE",{x:9.9,y:2.75,w:2.05,h:.3,fontSize:14,bold:true,color:C.blue,align:"center",margin:0});s.addText("1 hipótese\n1 justificativa\n1 evidência necessária",{x:9.85,y:3.35,w:2.15,h:1.35,fontSize:18,bold:true,color:C.ink,align:"center",valign:"mid",margin:0});footer(s);notes(s,"Votação argumentada. Aceite hipóteses concorrentes; cobre a evidência que as diferenciaria.");
}
{
 const s=pptx.addSlide();s.background={color:"0D2235"};s.addText("EVIDÊNCIA 1",{x:.7,y:.42,w:4.8,h:.28,fontSize:13,bold:true,color:"7DE0D8",charSpacing:1,margin:0});s.addText("O que o registro mostra — e o que não mostra?",{x:.7,y:.84,w:11.9,h:.72,fontSize:30,bold:true,color:C.white,margin:0,fit:"shrink"});
 s.addShape(pptx.ShapeType.roundRect,{x:.8,y:1.9,w:7.7,h:3.75,fill:{color:"071720"},line:{color:"31556D",width:1.5}});s.addText("09:16:52  HMI-01  login_success  operador_turno\n09:17:03  PLC-01  comm_timeout   3200 ms\n09:17:05  LINE-01 state_change RUN → STOP\n09:17:08  HMI-01  alarm_ack      ALM-204",{x:1.15,y:2.42,w:7,h:2.3,fontFace:"Courier New",fontSize:18,color:"D8F3EA",breakLine:false,margin:0});
 s.addText("OBSERVE",{x:9.15,y:2.05,w:2.7,h:.3,fontSize:14,bold:true,color:"7DE0D8",margin:0});s.addText("Ordem temporal\nOrigem do evento\nLacunas do registro",{x:9.15,y:2.65,w:3,h:1.55,fontSize:21,bold:true,color:C.white,margin:0});s.addText("Correlação não prova causa.",{x:9.15,y:4.85,w:3,h:.55,fontSize:16,color:"FFD19A",margin:0});footer(s,"Evidência fictícia preparada para a disciplina");notes(s,"Peça que marquem observação, inferência e lacuna com símbolos diferentes. Resposta esperada: há sequência, mas não autoria nem causalidade comprovadas.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Conceitos","Do evento ao risco","Use os termos para explicar a evidência, não para decorar definições.");
 const items=[["AMEAÇA","Condição capaz de causar dano",C.red],["EVENTO","Ocorrência observável",C.blue],["INCIDENTE","Evento que compromete objetivos",C.amber],["CONSEQUÊNCIA","Efeito sobre processo e pessoas",C.cyan],["RISCO","Incerteza sobre probabilidade e impacto",C.navy]];
 items.forEach(([h,b,c],i)=>{const x=.5+i*2.55;s.addShape(pptx.ShapeType.roundRect,{x,y:2.45,w:2.28,h:2.5,fill:{color:C.white},line:{color:c,width:2}});s.addText(h,{x:x+.15,y:2.75,w:1.98,h:.34,fontSize:14,bold:true,color:c,align:"center",margin:0});s.addText(b,{x:x+.19,y:3.42,w:1.9,h:1.05,fontSize:17,color:C.ink,align:"center",valign:"mid",margin:0,fit:"shrink"});});footer(s,"NIST CSF 2.0; NIST SP 800-82 Rev. 3");notes(s,"Construa as definições a partir do log. Mostre que nem todo evento é incidente e que risco orienta decisão antes e depois do fato.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Impacto","CIA e AAA mudam quando o software move o mundo","Em OT, disponibilidade e safety condicionam a resposta.");
 const cols=[["CIA","Confidencialidade\nIntegridade\nDisponibilidade",C.blue],["AAA","Autenticação\nAutorização\nAccounting (registro)",C.cyan],["PROCESSO","Qualidade\nProdução\nSafety",C.red]];cols.forEach(([h,b,c],i)=>{const x=.75+i*4.12;s.addShape(pptx.ShapeType.roundRect,{x,y:2.35,w:3.72,h:2.85,fill:{color:i===2?"FDECEA":C.paper},line:{color:c,width:2}});s.addText(h,{x:x+.25,y:2.7,w:3.2,h:.4,fontSize:20,bold:true,color:c,align:"center",margin:0});s.addText(b,{x:x+.3,y:3.35,w:3.1,h:1.35,fontSize:20,color:C.ink,align:"center",valign:"mid",margin:0});});s.addText("Pergunta de engenharia: o controle reduz o risco sem criar uma condição insegura?",{x:1.05,y:5.65,w:11.2,h:.55,fontSize:21,bold:true,color:C.navy,align:"center",margin:0});footer(s,"NIST SP 800-82 Rev. 3");notes(s,"Defina accounting como rastreabilidade de ações. Diferencie security de safety com exemplos do cenário.");
}
{
 const s=pptx.addSlide();s.background={color:C.navy};s.addText("CHECKPOINT 2",{x:.8,y:.7,w:4,h:.3,fontSize:14,bold:true,color:"7DE0D8",charSpacing:1.2,margin:0});s.addText("Você isolaria a HMI agora?",{x:.8,y:1.45,w:10.8,h:.9,fontSize:38,bold:true,color:C.white,margin:0});
 const opts=[["SIM","reduz possível propagação"],["NÃO","pode comprometer operação"],["CONDICIONAL","depende de evidência e estado seguro"]];opts.forEach(([h,b],i)=>{const x=.8+i*4.05;s.addShape(pptx.ShapeType.roundRect,{x,y:3,w:3.55,h:2,fill:{color:["174C76","12635F","70461B"][i]},line:{color:C.white,width:1}});s.addText(h,{x:x+.25,y:3.35,w:3.05,h:.35,fontSize:17,bold:true,color:C.white,align:"center",margin:0});s.addText(b,{x:x+.3,y:4,w:2.95,h:.6,fontSize:17,color:C.white,align:"center",margin:0});});s.addText("Justifique com risco, continuidade e safety.",{x:.9,y:6.35,w:11.3,h:.4,fontSize:18,color:"D6E5F0",align:"center",margin:0});notes(s,"Não existe resposta universal. A boa resposta explicita estado do processo, redundância, impacto e evidência disponível.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Resposta inicial","Preservar o processo e aumentar a certeza","A primeira intervenção deve ser reversível e observável.");
 const steps=[["1","ESTABILIZAR","Confirmar estado seguro"],["2","PRESERVAR","Salvar logs e horário"],["3","CORRELACIONAR","HMI, PLC e rede"],["4","DECIDIR","Conter com autorização"],["5","VALIDAR","Processo + telemetria"]];steps.forEach(([n,h,b],i)=>{const x=.45+i*2.58;s.addShape(pptx.ShapeType.roundRect,{x,y:2.45,w:2.3,h:2.55,fill:{color:C.white},line:{color:i===0?C.red:C.line,width:i===0?2:1}});s.addText(n,{x:x+.78,y:2.7,w:.72,h:.55,fontSize:22,bold:true,color:C.white,fill:{color:i===0?C.red:C.blue},align:"center",margin:0});s.addText(h,{x:x+.15,y:3.48,w:2,h:.32,fontSize:14,bold:true,color:C.navy,align:"center",margin:0});s.addText(b,{x:x+.18,y:4.05,w:1.94,h:.55,fontSize:16,color:C.ink,align:"center",margin:0});});footer(s,"NIST CSF 2.0; NIST SP 800-82 Rev. 3");notes(s,"Plano alternativo: se o laboratório falhar, use o log e a tabela de evidências do PDF. Nenhuma ação deve atingir sistemas externos.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Prática","Construa uma linha do tempo defensável","O roteiro contém o pacote de evidências, regras e critérios.");
 s.addShape(pptx.ShapeType.roundRect,{x:.8,y:2.2,w:7.55,h:3.65,fill:{color:"E7F5F3"},line:{color:C.cyan,width:2}});s.addText("MISSÃO",{x:1.2,y:2.65,w:2,h:.3,fontSize:15,bold:true,color:C.cyan,margin:0});s.addText("Ordene eventos, compare hipóteses e recomende a próxima coleta segura.",{x:1.2,y:3.25,w:6.3,h:1.4,fontSize:27,bold:true,color:C.navy,margin:0,fit:"shrink"});
 s.addText("ENTREGA",{x:9.1,y:2.55,w:2.6,h:.3,fontSize:15,bold:true,color:C.blue,margin:0});s.addText("Linha do tempo\nHipótese principal\nHipótese alternativa\nPróxima evidência",{x:9.1,y:3.1,w:3.1,h:1.75,fontSize:20,bold:true,color:C.navy,margin:0});s.addText("Somente dados fictícios e sanitizados",{x:9.1,y:5.25,w:3.1,h:.5,fontSize:14,color:C.red,margin:0});footer(s);notes(s,"Distribua o PDF. Confirme escopo e critério de parada antes de iniciar os 52 minutos práticos.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Síntese","Evidência antes da certeza","Uma decisão profissional explica limites, impacto e como será validada.");
 const chain=[["OBSERVAR",C.blue],["FORMULAR",C.cyan],["CORRELACIONAR",C.amber],["INTERVIR",C.red],["VALIDAR",C.navy]];chain.forEach(([t,c],i)=>{const x=.45+i*2.58;s.addShape(pptx.ShapeType.roundRect,{x,y:2.65,w:2.3,h:1.2,fill:{color:c},line:{color:c}});s.addText(t,{x:x+.12,y:3.03,w:2.06,h:.35,fontSize:16,bold:true,color:C.white,align:"center",margin:0});});s.addText("Transferência: em um hospital ou edifício inteligente, qual consequência mudaria sua prioridade?",{x:1.05,y:4.8,w:11.2,h:.9,fontSize:24,bold:true,color:C.navy,align:"center",margin:0});footer(s,"NIST CSF 2.0; NIST SP 800-82 Rev. 3; NICE Framework");notes(s,"Fechamento: peça uma frase no formato 'Eu afirmo..., porque a evidência..., mas ainda falta...'.");
}
await pptx.writeFile({fileName:resolve(slideDir,"A01-o-incidente-que-parou-a-linha.pptx")});

const H=(text,level=HeadingLevel.HEADING_1)=>new Paragraph({text,heading:level,spacing:{before:220,after:100},keepNext:true});
const P=(text,opts={})=>new Paragraph({children:[new TextRun({text,size:24,color:C.ink})],spacing:{after:120,line:330},...opts});
const Cell=(text,fill="FFFFFF",bold=false,color=C.ink)=>new TableCell({shading:{type:ShadingType.CLEAR,fill},margins:{top:130,bottom:130,left:150,right:150},children:[new Paragraph({children:[new TextRun({text,bold,color,size:23})],spacing:{after:0,line:300}})]});
const callout=(label,text,color)=>new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[new TableCell({shading:{type:ShadingType.CLEAR,fill:color},margins:{top:150,bottom:150,left:180,right:180},children:[new Paragraph({children:[new TextRun({text:label.toUpperCase(),bold:true,color:"FFFFFF",size:23})],spacing:{after:70}}),new Paragraph({children:[new TextRun({text,color:"FFFFFF",size:24})],spacing:{line:320}})]})]})]});
const bullets=(items)=>items.map(text=>new Paragraph({children:[new TextRun({text,size:24,color:C.ink})],bullet:{level:0},spacing:{after:90,line:320}}));
const doc=new Document({creator:"Curso de Segurança Digital",title:"A01 — O incidente que parou a linha — prática",styles:{default:{document:{run:{font:"Arial",size:24,color:C.ink},paragraph:{spacing:{line:330}}}},paragraphStyles:[{id:"Title",name:"Title",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Arial",size:42,bold:true,color:C.navy},paragraph:{spacing:{after:180}}},{id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Arial",size:31,bold:true,color:C.navy},paragraph:{spacing:{before:240,after:100},outlineLevel:0}},{id:"Heading2",name:"Heading 2",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Arial",size:27,bold:true,color:C.blue},paragraph:{spacing:{before:180,after:80},outlineLevel:1}}]},sections:[{properties:{page:{margin:{top:800,right:800,bottom:800,left:800}}},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:"A01 • Segurança Digital • roteiro do estudante",font:"Arial",size:18,color:C.grey})]})]})},children:[
 new Paragraph({children:[new TextRun({text:"A01 • FUNDAMENTOS E RISCO",bold:true,color:C.cyan,size:23})],spacing:{after:120}}),new Paragraph({text:"O incidente que parou a linha",style:"Title"}),P("Missão: reconstruir uma linha do tempo preliminar e defender a próxima ação de coleta sem comprometer o processo."),
 new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[Cell("Duração\n52 minutos",C.pale,true),Cell("Organização\nduplas",C.pale,true),Cell("Entrega\num PDF por dupla",C.pale,true)]})]}),
 H("Objetivos"),...bullets(["Distinguir observação, hipótese e conclusão ao analisar registros.","Relacionar eventos a impacto em TI, OT e safety.","Justificar uma próxima coleta ou contenção com evidência e restrições."]),
 H("Pré-requisitos e recursos"),...bullets(["Página MkDocs A01 consultável durante a atividade.","Este roteiro e o pacote de evidências nele contido.","Editor de texto ou papel para organizar a linha do tempo.","Juice Shop local é opcional; nenhuma exploração é necessária nesta aula."]),
 callout("Atenção","Escopo autorizado: somente os dados fictícios deste roteiro e o ambiente da disciplina. Não teste endereços externos. Pare se o laboratório apresentar efeito fora do cenário e avise o professor.",C.red),
 H("Hipótese inicial"),P("Antes de continuar, registre: (1) a causa mais provável; (2) por que ela explicaria a parada; (3) qual evidência poderia refutá-la."),P("Hipótese: __________________________________________________________________"),P("Evidência necessária: ________________________________________________________"),
 new Paragraph({children:[new PageBreak()]}),H("Etapa 1 — Ordenar sem interpretar (10 min)",HeadingLevel.HEADING_2),P("Os relógios foram sincronizados para esta atividade. Ordene os registros e marque cada linha como evento de autenticação, comunicação, processo ou resposta."),
 new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({tableHeader:true,children:[Cell("Horário",C.navy,true,"FFFFFF"),Cell("Fonte",C.navy,true,"FFFFFF"),Cell("Registro",C.navy,true,"FFFFFF")]}),...[ ["09:17:08","HMI-01","alarm_ack ALM-204"],["09:16:52","HMI-01","login_success operador_turno"],["09:17:05","LINE-01","state_change RUN → STOP"],["09:17:03","PLC-01","comm_timeout 3200 ms"],["09:18:11","NET-SENSOR","flux HMI-01 → PLC-01 restabelecido"] ].map(r=>new TableRow({children:r.map(x=>Cell(x))}))]}),
 callout("Evidência","Entregue uma linha do tempo ordenada. Para cada evento, escreva uma frase dizendo o que ele mostra diretamente — sem atribuir causa ou autoria.",C.blue),
 H("Etapa 2 — Comparar hipóteses (15 min)",HeadingLevel.HEADING_2),P("Compare pelo menos duas explicações. Uma boa hipótese explica vários eventos e declara o que ainda não consegue explicar."),
 new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({tableHeader:true,children:[Cell("Hipótese",C.navy,true,"FFFFFF"),Cell("Evidência favorável",C.navy,true,"FFFFFF"),Cell("Lacuna ou contradição",C.navy,true,"FFFFFF")]}),new TableRow({children:[Cell("Falha de comunicação"),Cell(""),Cell("")]}),new TableRow({children:[Cell("Ação indevida ou credencial comprometida"),Cell(""),Cell("")]})]}),
 callout("Pista","Login anterior ao evento não prova que a pessoa autenticada causou a parada. Sequência temporal é necessária para correlação, mas não basta para causalidade.",C.cyan),
 H("Etapa 3 — Decidir a próxima coleta (15 min)",HeadingLevel.HEADING_2),P("Escolha uma ação: preservar os logs da HMI; capturar tráfego entre HMI e PLC; consultar o histórico de alarmes; ou isolar a HMI. Compare benefício, risco operacional e reversibilidade."),
 new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({tableHeader:true,children:[Cell("Opção",C.navy,true,"FFFFFF"),Cell("Melhor uso",C.navy,true,"FFFFFF"),Cell("Evidência gerada",C.navy,true,"FFFFFF"),Cell("Limitação/risco",C.navy,true,"FFFFFF")]}),...["Preservar logs","Capturar tráfego","Histórico de alarmes","Isolar HMI"].map(x=>new TableRow({children:[Cell(x),Cell(""),Cell(""),Cell("")]}))]}),
 callout("Decisão","Registre a ação escolhida, a autorização necessária, o critério de parada e por que ela preserva disponibilidade e safety.",C.amber),
 H("Etapa 4 — Validar e comunicar (12 min)",HeadingLevel.HEADING_2),...bullets(["Revise se a conclusão excede o que as evidências sustentam.","Mantenha uma hipótese alternativa plausível.","Indique qual novo resultado confirmaria ou enfraqueceria a hipótese principal.","Sanitize a entrega: não inclua credenciais, tokens, IPs públicos ou dados pessoais."]),
 H("Entrega"),P("Envie no Google Classroom um PDF chamado A01-dupla-NN.pdf contendo: hipótese inicial; linha do tempo; tabela de hipóteses; decisão justificada; e uma reflexão de até cinco linhas."),
 H("Critérios de sucesso"),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({tableHeader:true,children:[Cell("Critério",C.navy,true,"FFFFFF"),Cell("Atendeu",C.navy,true,"FFFFFF"),Cell("Parcial",C.navy,true,"FFFFFF")]}),...[ ["Linha do tempo","Ordenada; fatos separados de inferências","Há ordem, mas mistura fato e inferência"],["Hipóteses","Duas explicações comparadas com lacunas","Só uma hipótese ou comparação superficial"],["Decisão","Considera evidência, risco e safety","Justificativa incompleta"],["Comunicação","Limites e próxima validação explícitos","Conclusão sem limites claros"] ].map(r=>new TableRow({children:r.map(x=>Cell(x))}))]}),
 H("Limpeza e encerramento"),...bullets(["Feche os arquivos do pacote e descarte anotações com dados não sanitizados.","Se o Juice Shop local foi aberto, encerre o processo ou container.","Confirme que nenhum serviço vulnerável ficou acessível fora do laboratório."]),
 H("Extensão opcional"),P("Crie um evento adicional que diferenciaria as duas hipóteses sem revelar a resposta. Troque com outra dupla e avalie se o novo dado realmente muda a decisão."),
 H("Transferência"),P("Em um hospital, edifício inteligente ou sistema de transporte, qual consequência alteraria a prioridade entre preservar evidência e estabilizar o processo?"),
 H("Fontes oficiais"),...bullets(["NIST Cybersecurity Framework 2.0 — https://www.nist.gov/cyberframework","NIST SP 800-82 Rev. 3 — https://csrc.nist.gov/pubs/sp/800/82/r3/final"])
]}]});
await writeFile(resolve(activityDir,"A01-o-incidente-que-parou-a-linha.docx"),await Packer.toBuffer(doc));
