import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const pptxgen = require("pptxgenjs");
import { AlignmentType, Document, Footer, HeadingLevel, Packer, PageBreak, Paragraph, ShadingType, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
const slug = "A02-ativos-ameacas-e-vulnerabilidades";
const slideRoot = resolve(root, "slides", slug);
const activityRoot = resolve(root, "atividades", slug);
await Promise.all([
  mkdir(resolve(slideRoot, "fonte"), { recursive: true }), mkdir(resolve(slideRoot, "assets"), { recursive: true }), mkdir(resolve(slideRoot, "exportados"), { recursive: true }),
  mkdir(resolve(activityRoot, "fonte"), { recursive: true }), mkdir(resolve(activityRoot, "assets"), { recursive: true }), mkdir(resolve(activityRoot, "pdf"), { recursive: true }),
]);

const C={navy:"12304A",blue:"0B65C2",cyan:"087F7A",amber:"B75D00",red:"B42318",paper:"F4F7FA",ink:"172B4D",white:"FFFFFF",grey:"4B5E71",line:"C9D4DF",pale:"E7F0F8",green:"26734D"};
const pptx=new pptxgen(); pptx.layout="LAYOUT_WIDE"; pptx.author="Curso de Segurança Digital"; pptx.title="A02 — Ativos, ameaças e vulnerabilidades"; pptx.lang="pt-BR"; pptx.theme={headFontFace:"Arial",bodyFontFace:"Arial",lang:"pt-BR"};
const notes=(s,t)=>s.addNotes(t);
const footer=(s,src="NIST CSF 2.0 • CWE • CVE")=>{s.addShape(pptx.ShapeType.line,{x:.6,y:7.08,w:12.05,h:0,line:{color:C.line,width:1}});s.addText("A02  •  Segurança Digital",{x:.65,y:7.14,w:4,h:.2,fontSize:10,color:C.grey,margin:0});s.addText(src,{x:6.5,y:7.14,w:6.15,h:.2,fontSize:9,color:C.grey,align:"right",margin:0});};
const head=(s,k,t,sub="")=>{s.addText(k.toUpperCase(),{x:.7,y:.42,w:4.8,h:.28,fontSize:13,bold:true,color:C.cyan,charSpacing:1,margin:0});s.addText(t,{x:.7,y:.84,w:11.9,h:.72,fontSize:30,bold:true,color:C.navy,margin:0,fit:"shrink"});if(sub)s.addText(sub,{x:.72,y:1.65,w:11.4,h:.44,fontSize:17,color:C.grey,margin:0,fit:"shrink"});};
const card=(s,x,y,w,h,title,body,color=C.blue)=>{s.addShape(pptx.ShapeType.roundRect,{x,y,w,h,fill:{color:C.white},line:{color,width:2}});s.addText(title,{x:x+.22,y:y+.25,w:w-.44,h:.3,fontSize:14,bold:true,color,margin:0});s.addText(body,{x:x+.22,y:y+.82,w:w-.44,h:h-1.05,fontSize:18,bold:true,color:C.ink,margin:0,fit:"shrink",valign:"mid"});};

{
 const s=pptx.addSlide();s.background={color:C.navy};s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:.22,h:7.5,fill:{color:C.cyan},line:{color:C.cyan}});s.addText("A02  •  FUNDAMENTOS E RISCO",{x:.8,y:.72,w:5.5,h:.32,fontSize:14,bold:true,color:"7DE0D8",charSpacing:1.2,margin:0});s.addText("O que realmente\nestá exposto?",{x:.8,y:1.3,w:7.1,h:1.55,fontSize:40,bold:true,color:C.white,margin:0});s.addText("Na A01, aprendemos a não confundir correlação com causa. Agora o servidor entrega um arquivo interno: precisamos ligar a evidência ao ativo, à fraqueza e à consequência antes de priorizar a resposta.",{x:.82,y:3.08,w:7.35,h:1.5,fontSize:18.5,color:"E6EEF5",margin:0,fit:"shrink"});s.addText("O código 200 prova entrega; ainda não explica alcance, intenção ou impacto.",{x:.82,y:4.85,w:7.25,h:.5,fontSize:17,bold:true,color:"7DE0D8",margin:0});s.addShape(pptx.ShapeType.roundRect,{x:9.05,y:1.45,w:3.25,h:3.15,fill:{color:"071720"},line:{color:"7DE0D8",width:2}});s.addText("HTTP/1.1\n200 OK",{x:9.38,y:2.18,w:2.6,h:1.15,fontFace:"Courier New",fontSize:27,bold:true,color:C.white,align:"center",valign:"mid",margin:0});s.addText("2 × 52 min  •  investigação em duplas",{x:.82,y:6.55,w:5.2,h:.3,fontSize:14,color:"C7D6E4",margin:0});notes(s,"Retome a disciplina de evidência da A01. Mostre a resposta por 30 segundos e não aceite vulnerabilidade ou ataque como fatos antes de discutir ativo e consequência.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Objetivo da aula","Aprender a explicar uma exposição observada","Não vamos procurar falhas: vamos analisar juntos uma evidência conhecida.");const steps=[["1","OBSERVAR","o servidor entregou o quê?",C.blue],["2","NOMEAR","qual ativo e quais conceitos?",C.cyan],["3","DECIDIR","qual controle faz sentido?",C.amber],["4","VALIDAR","como provar que melhorou?",C.green]];steps.forEach(([n,h,b,c],i)=>{const x=.55+i*3.15;s.addShape(pptx.ShapeType.roundRect,{x,y:2.3,w:2.83,h:2.75,fill:{color:C.white},line:{color:c,width:2}});s.addText(n,{x:x+.96,y:2.58,w:.72,h:.55,fontSize:22,bold:true,color:C.white,fill:{color:c},align:"center",margin:0});s.addText(h,{x:x+.2,y:3.48,w:2.43,h:.3,fontSize:15,bold:true,color:c,align:"center",margin:0});s.addText(b,{x:x+.3,y:4.08,w:2.23,h:.55,fontSize:17,bold:true,color:C.navy,align:"center",margin:0});});s.addText("Ao final, você conseguirá escrever: evidência → ativo → hipótese de fraqueza → vulnerabilidade → consequência → controle → reteste.",{x:1.05,y:5.7,w:11.2,h:.62,fontSize:19,bold:true,color:C.navy,align:"center",margin:0});footer(s);notes(s,"Faça a ponte direta com o slide 1: temos um 200; a competência é transformar esse fato em uma decisão defensável, sem exigir descoberta autônoma.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Ambiente","Cada estudante abre o Juice Shop no próprio computador","127.0.0.1 significa esta máquina; não é um servidor fornecido pelo professor.");s.addShape(pptx.ShapeType.roundRect,{x:.7,y:2.12,w:7.7,h:3.9,fill:{color:"0D2235"},line:{color:"31556D"}});s.addText("POWERSHELL OU TERMINAL LINUX\n\ndocker pull bkimminich/juice-shop\n\ndocker run --rm -d --name juice-shop-a02\n-p 127.0.0.1:3000:3000 bkimminich/juice-shop",{x:1.05,y:2.55,w:6.95,h:2.85,fontFace:"Courier New",fontSize:16,color:"D8F3EA",margin:0,fit:"shrink"});s.addText("ABRA",{x:9.05,y:2.45,w:2.8,h:.3,fontSize:14,bold:true,color:C.blue,margin:0});s.addText("http://127.0.0.1:3000",{x:9.05,y:2.95,w:3.15,h:.7,fontSize:21,bold:true,color:C.navy,margin:0,fit:"shrink"});s.addText("POR QUE LOCAL?",{x:9.05,y:4.08,w:2.8,h:.3,fontSize:14,bold:true,color:C.cyan,margin:0});s.addText("A aplicação é vulnerável de propósito. Mantê-la em 127.0.0.1 limita o acesso à própria máquina.",{x:9.05,y:4.55,w:3.2,h:1.05,fontSize:16.5,bold:true,color:C.navy,margin:0,fit:"shrink"});footer(s,"OWASP Juice Shop — guia oficial de execução com Docker");notes(s,"Só aqui introduza o escopo. Confirme Docker ativo. Se houver falha, use a evidência impressa; não peça que o estudante procure outro alvo.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Observação guiada","Uma URL, uma requisição e limites claros","Professor e turma executam juntos; ninguém precisa descobrir uma rota.");s.addShape(pptx.ShapeType.roundRect,{x:.65,y:2.1,w:7.55,h:3.95,fill:{color:"0D2235"},line:{color:"31556D"}});s.addText("ABRA NO NAVEGADOR\nhttp://127.0.0.1:3000/ftp/acquisitions.md\n\nREQUISIÇÃO OBSERVADA\nGET /ftp/acquisitions.md HTTP/1.1\nHost: 127.0.0.1:3000\n\nRESPOSTA ESPERADA\nHTTP/1.1 200 OK • text/markdown",{x:1.02,y:2.45,w:6.85,h:2.95,fontFace:"Courier New",fontSize:15.5,color:"D8F3EA",margin:0,fit:"shrink"});s.addText("ANTES DE EXPLICAR",{x:8.75,y:2.3,w:3.25,h:.3,fontSize:13,bold:true,color:C.blue,margin:0});s.addText("1. O que foi observado?\n2. Qual informação tem valor?\n3. O que ainda é hipótese?",{x:8.75,y:2.83,w:3.55,h:1.45,fontSize:18.5,bold:true,color:C.navy,margin:0});s.addShape(pptx.ShapeType.roundRect,{x:8.72,y:4.65,w:3.7,h:1.05,fill:{color:C.pale},line:{color:C.line}});s.addText("200 prova entrega naquela requisição — não prova causa, intenção ou alcance.",{x:9,y:4.9,w:3.15,h:.52,fontSize:14.5,bold:true,color:C.navy,align:"center",margin:0});footer(s,"Rota validada na imagem oficial do OWASP Juice Shop");notes(s,"Execute junto com a turma. Se a versão não responder como esperado, use a captura/evidência do PDF. Não peça enumeração nem descoberta de caminhos.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Ativo","O que tem valor nesta evidência?","Comece pelo que perderia valor — não pela técnica nem pelo equipamento.");const data=[["CANDIDATO","POR QUE PODE SER ATIVO?","EVIDÊNCIA NO CASO"],["informação de aquisição","apoia decisões e deveria permanecer restrita","conteúdo declara confidencialidade"],["arquivo acquisitions.md","armazena e transporta a informação","nome, caminho e tipo markdown"],["rota/serviço web","torna o recurso acessível","GET recebeu resposta 200"],["container Juice Shop","executa a aplicação do laboratório","docker ps + endereço local"]];s.addTable(data.map(r=>r.map(text=>({text}))),{x:.65,y:2.08,w:12.05,h:3.62,border:{color:C.line,width:1},fill:C.white,color:C.ink,fontSize:15,margin:.1,rowH:.7,bold:false,valign:"mid",autoFit:false});s.addShape(pptx.ShapeType.roundRect,{x:1.05,y:5.92,w:11.15,h:.55,fill:{color:C.pale},line:{color:C.line}});s.addText("Ativo não é sinônimo de servidor: informação, arquivo, serviço e plataforma sustentam funções diferentes.",{x:1.3,y:6.08,w:10.65,h:.25,fontSize:15.5,bold:true,color:C.navy,align:"center",margin:0});footer(s,"NIST Cybersecurity Framework 2.0 — ID.AM");notes(s,"Construa as quatro linhas com a turma. Não introduza OT aqui; deixe a comparação para o fechamento.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Exemplo construído","Da evidência aos conceitos necessários","Primeiro modele a frase; depois peça que as duplas a critiquem e completem.");const items=[["1 • ATIVO","informação do arquivo acquisitions.md",C.blue],["2 • OBSERVAÇÃO","GET sem login recebeu 200 + markdown",C.green],["3 • FRAQUEZA — HIPÓTESE","arquivo em área servida ou autorização ausente",C.amber],["4 • VULNERABILIDADE","esta implantação permite acesso não autenticado",C.cyan],["5 • AMEAÇA","usuário não autorizado obtém a informação",C.red],["6 • CONSEQUÊNCIA","divulgação de planos fictícios de aquisição",C.navy]];items.forEach(([h,b,c],i)=>{const col=i%2,row=Math.floor(i/2),x=.7+col*6.15,y=1.98+row*1.48;card(s,x,y,5.72,1.38,h,b,c);});footer(s,"CWE — classes de fraqueza; não atribuir CVE sem fonte");notes(s,"Leia de cima para baixo. Pergunte em qual linha começamos a inferir. Depois apague verbalmente uma linha e peça à turma que a reconstrua.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Controle","Uma medida que modifica o risco","O controle entra depois que entendemos ativo, exposição e consequência.");const controls=[["PREVENTIVO","evita ou dificulta","retirar o arquivo da área pública",C.blue],["DETECTIVO","torna o evento observável","registrar e alertar acesso à rota",C.amber],["CORRETIVO","remove a causa ou restaura condição esperada","corrigir publicação ou autorização",C.red],["RECUPERAÇÃO","restabelece serviço/dados após impacto","restaurar versão íntegra e configuração",C.green]];controls.forEach(([h,q,e,c],i)=>{const x=.55+i*3.16;s.addShape(pptx.ShapeType.roundRect,{x,y:2.15,w:2.88,h:3.35,fill:{color:C.white},line:{color:c,width:2}});s.addText(h,{x:x+.2,y:2.48,w:2.48,h:.3,fontSize:14,bold:true,color:c,align:"center",margin:0});s.addText(q,{x:x+.28,y:3.1,w:2.32,h:.58,fontSize:17,bold:true,color:C.navy,align:"center",margin:0});s.addShape(pptx.ShapeType.line,{x:x+.45,y:3.9,w:1.98,h:0,line:{color:C.line,width:1}});s.addText(e,{x:x+.28,y:4.22,w:2.32,h:.78,fontSize:15.5,color:C.ink,align:"center",margin:0,fit:"shrink"});});s.addText("Controles podem atuar em camadas. Detectar não substitui prevenir ou corrigir quando a exposição permanece.",{x:1.05,y:5.9,w:11.2,h:.52,fontSize:18,bold:true,color:C.navy,align:"center",margin:0});footer(s,"NIST CSF 2.0 — Protect, Detect, Respond e Recover");notes(s,"Construa a definição antes das categorias. Pergunte como cada medida altera probabilidade, consequência ou tempo de detecção.");
}
{
 const s=pptx.addSlide();s.background={color:C.navy};s.addText("CHECKPOINT 2",{x:.8,y:.7,w:4,h:.3,fontSize:14,bold:true,color:"7DE0D8",charSpacing:1.2,margin:0});s.addText("Qual controle você defenderia?",{x:.8,y:1.45,w:10.8,h:.9,fontSize:38,bold:true,color:C.white,margin:0});const opts=[["REMOVER","recurso não deveria ser servido"],["AUTORIZAR","papel específico precisa acessar"],["MONITORAR","correção imediata é inviável"]];opts.forEach(([h,b],i)=>{const x=.8+i*4.05;s.addShape(pptx.ShapeType.roundRect,{x,y:3,w:3.55,h:2,fill:{color:["174C76","12635F","70461B"][i]},line:{color:C.white,width:1}});s.addText(h,{x:x+.25,y:3.35,w:3.05,h:.35,fontSize:17,bold:true,color:C.white,align:"center",margin:0});s.addText(b,{x:x+.3,y:4,w:2.95,h:.62,fontSize:17,color:C.white,align:"center",margin:0});});s.addText("Declare a premissa e a evidência de reteste.",{x:.9,y:6.35,w:11.3,h:.4,fontSize:18,color:"D6E5F0",align:"center",margin:0});notes(s,"Monitorar não substitui correção. Aceite escolhas condicionadas à função do arquivo e à arquitetura.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Registro","Uma frase profissional liga os conceitos","A dupla receberá pontos de partida e deverá justificar limites e evidências.");s.addShape(pptx.ShapeType.roundRect,{x:.75,y:2.18,w:11.85,h:2.3,fill:{color:C.white},line:{color:C.blue,width:2}});s.addText("Nesta implantação, uma requisição GET sem autenticação recebeu 200 e entregou o arquivo acquisitions.md. Isso expõe informação fictícia de aquisição a um usuário não autorizado. A condição provável ainda precisa ser confirmada na arquitetura.",{x:1.15,y:2.68,w:11.05,h:1.25,fontSize:21,bold:true,color:C.navy,align:"center",valign:"mid",margin:0,fit:"shrink"});s.addText("A dupla deve marcar na frase:",{x:1.15,y:4.95,w:3.2,h:.3,fontSize:14,bold:true,color:C.cyan,margin:0});s.addText("evidência observada  •  ativo  •  vulnerabilidade concreta  •  ameaça  •  consequência  •  hipótese de fraqueza",{x:1.15,y:5.42,w:11.05,h:.52,fontSize:17.5,bold:true,color:C.navy,margin:0,align:"center"});footer(s);notes(s,"Leia a frase pausadamente e peça que a turma identifique cada trecho. Mostre que a hipótese de fraqueza não deve ser escrita como causa confirmada.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Prática","Suba localmente, investigue e encerre com segurança","Cada estudante acessa seu próprio container em http://127.0.0.1:3000.");s.addShape(pptx.ShapeType.roundRect,{x:.65,y:2.15,w:7.85,h:3.85,fill:{color:"E7F5F3"},line:{color:C.cyan,width:2}});s.addText("PREPARAÇÃO — POWERSHELL OU TERMINAL LINUX",{x:1.02,y:2.5,w:6.8,h:.3,fontSize:13,bold:true,color:C.cyan,margin:0});s.addText("docker pull bkimminich/juice-shop\ndocker run --rm -d --name juice-shop-a02 -p 127.0.0.1:3000:3000 bkimminich/juice-shop",{x:1.02,y:3.02,w:6.8,h:1.25,fontFace:"Courier New",fontSize:15.5,color:C.navy,margin:0,fit:"shrink"});s.addText("ABRA  http://127.0.0.1:3000",{x:1.02,y:4.66,w:6.6,h:.42,fontSize:19,bold:true,color:C.blue,margin:0});s.addText("ENCERRE  docker stop juice-shop-a02",{x:1.02,y:5.3,w:6.6,h:.34,fontSize:15,bold:true,color:C.red,margin:0});s.addText("ENTREGA",{x:9.05,y:2.45,w:2.6,h:.3,fontSize:15,bold:true,color:C.blue,margin:0});s.addText("Inventário do Juice Shop\nEvidência interpretada\nControle justificado\nReteste definido",{x:9.05,y:3.02,w:3.2,h:1.75,fontSize:18.5,bold:true,color:C.navy,margin:0});s.addText("Sem credenciais ou dados reais",{x:9.05,y:5.2,w:3.2,h:.5,fontSize:14,color:C.red,margin:0});footer(s);notes(s,"Confirme Docker ativo e URL 127.0.0.1. O PDF contém Windows/Linux, diagnóstico de porta, logs e limpeza.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Síntese","Inventário orienta a prioridade","A terminologia conecta evidência, causa, consequência, ação e validação.");const chain=[["INVENTARIAR",C.blue],["OBSERVAR",C.cyan],["EXPLICAR",C.amber],["TRATAR",C.red],["RETESTAR",C.green]];chain.forEach(([t,c],i)=>{const x=.45+i*2.58;s.addShape(pptx.ShapeType.roundRect,{x,y:2.65,w:2.3,h:1.2,fill:{color:c},line:{color:c}});s.addText(t,{x:x+.12,y:3.03,w:2.06,h:.35,fontSize:15,bold:true,color:C.white,align:"center",margin:0});});s.addText("Transferência: qual consequência física mudaria sua prioridade em uma HMI?",{x:1.05,y:4.8,w:11.2,h:.9,fontSize:24,bold:true,color:C.navy,align:"center",margin:0});footer(s,"NIST CSF 2.0; CWE; CVE; OWASP Juice Shop");notes(s,"Feche com: Priorizamos o ativo..., porque..., e validaremos o controle por...");
}
await pptx.writeFile({fileName:resolve(slideRoot,"fonte","A02-ativos-ameacas-e-vulnerabilidades.pptx")});

const H=(text,level=HeadingLevel.HEADING_1)=>new Paragraph({text,heading:level,spacing:{before:220,after:100},keepNext:true});
const P=(text,opts={})=>new Paragraph({children:[new TextRun({text,size:24,color:C.ink})],spacing:{after:120,line:330},...opts});
const Code=(text)=>new Paragraph({children:[new TextRun({text,font:"Consolas",size:20,color:"D8F3EA"})],shading:{type:ShadingType.CLEAR,fill:"0D2235"},spacing:{before:50,after:110,line:280},indent:{left:180,right:180}});
const Cell=(text,fill="FFFFFF",bold=false,color=C.ink,width=null)=>new TableCell({width:width?{size:width,type:WidthType.DXA}:undefined,shading:{type:ShadingType.CLEAR,fill},margins:{top:120,bottom:120,left:150,right:150},children:[new Paragraph({children:[new TextRun({text,bold,color,size:22})],spacing:{after:0,line:290}})]});
const callout=(label,text,color)=>new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[new TableCell({shading:{type:ShadingType.CLEAR,fill:color},margins:{top:145,bottom:145,left:180,right:180},children:[new Paragraph({children:[new TextRun({text:label.toUpperCase(),bold:true,color:"FFFFFF",size:23})],spacing:{after:65}}),new Paragraph({children:[new TextRun({text,color:"FFFFFF",size:23})],spacing:{line:315}})]})]})]});
const bullets=(items)=>items.map(text=>new Paragraph({children:[new TextRun({text,size:24,color:C.ink})],bullet:{level:0},spacing:{after:85,line:315}}));
const tbl=(headers,rows,widths)=>new Table({width:{size:10300,type:WidthType.DXA},columnWidths:widths,rows:[new TableRow({tableHeader:true,children:headers.map((x,i)=>Cell(x,C.navy,true,"FFFFFF",widths[i]))}),...rows.map(r=>new TableRow({children:r.map((x,i)=>Cell(x,"FFFFFF",false,C.ink,widths[i]))}))]});
const doc=new Document({creator:"Curso de Segurança Digital",title:"A02 — Ativos, ameaças e vulnerabilidades — prática",styles:{default:{document:{run:{font:"Arial",size:24,color:C.ink},paragraph:{spacing:{line:330}}}},paragraphStyles:[{id:"Title",name:"Title",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Arial",size:42,bold:true,color:C.navy},paragraph:{spacing:{after:180}}},{id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Arial",size:31,bold:true,color:C.navy},paragraph:{spacing:{before:240,after:100},outlineLevel:0}},{id:"Heading2",name:"Heading 2",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Arial",size:27,bold:true,color:C.blue},paragraph:{spacing:{before:180,after:80},outlineLevel:1}}]},sections:[{properties:{page:{margin:{top:800,right:800,bottom:800,left:800}}},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:"A02 • Segurança Digital • roteiro do estudante",font:"Arial",size:18,color:C.grey})]})]})},children:[
 new Paragraph({children:[new TextRun({text:"A02 • FUNDAMENTOS E RISCO",bold:true,color:C.cyan,size:23})],spacing:{after:120}}),new Paragraph({text:"O que realmente está exposto?",style:"Title"}),P("Missão: investigar uma exposição simples no Juice Shop local e produzir um registro que conecte ativo, fraqueza, vetor, consequência, controle e reteste."),
 tbl(["Duração","Organização","Entrega"],[["52 minutos","duplas; papéis rotativos","um PDF por dupla"]],[3400,3400,3500]),
 H("Objetivos"),...bullets(["Inventariar os ativos do ambiente Juice Shop relacionando função e consequência.","Distinguir ameaça, fraqueza, vulnerabilidade, exposição e exploit na evidência.","Priorizar o registro, escolher controle e definir validação reproduzível."]),
 H("Pré-requisitos e recursos"),...bullets(["A01 e página MkDocs A02 consultável durante a atividade.","Docker Desktop iniciado no Windows ou Docker Engine em execução no Linux.","Navegador com DevTools; Burp Community é opcional.","Acesso para baixar a imagem antes da aula; depois do download, a prática pode continuar localmente.","Este roteiro contém evidência alternativa para falha do ambiente."]),
 callout("Atenção","Escopo: somente o Juice Shop local fornecido. Não teste a demonstração pública, sistemas institucionais ou terceiros. Use dados fictícios. Pare se o destino divergir, houver dados reais ou o comportamento alcançar outro sistema.",C.red),
 H("Previsão inicial"),P("A rota será fornecida; não é preciso descobri-la. Antes de acessar, preveja: a requisição será aceita sem login? Que resposta indicaria entrega do arquivo? O que essa resposta ainda não permitiria concluir?"),P("Resposta esperada: __________________________________________________________"),P("Limite da conclusão: _________________________________________________________"),
 new Paragraph({children:[new PageBreak()]}),H("Etapa 1 — Subir o Juice Shop localmente (12 min)",HeadingLevel.HEADING_2),
 P("Os comandos Docker são iguais no PowerShell do Windows e no terminal Linux. No Windows, abra primeiro o Docker Desktop em modo de containers Linux. No Linux, confirme que o Docker Engine está ativo."),
 P("1. Confirme que o cliente consegue falar com o mecanismo Docker:"),Code("docker version"),
 P("2. Baixe a imagem oficial usada pelo guia do OWASP Juice Shop:"),Code("docker pull bkimminich/juice-shop"),
 P("3. Inicie um container acessível somente pela própria máquina:"),Code("docker run --rm -d --name juice-shop-a02 -p 127.0.0.1:3000:3000 bkimminich/juice-shop"),
 P("4. Confirme o estado e aguarde a coluna STATUS indicar que o container está em execução:"),Code("docker ps --filter name=juice-shop-a02"),
 callout("Atenção","O vínculo 127.0.0.1 limita o serviço ao computador local. Não substitua por 0.0.0.0, não publique a porta no roteador e não use a demonstração pública do Juice Shop como alvo.",C.red),
 H("Windows — PowerShell",HeadingLevel.HEADING_2),...bullets(["Inicie o Docker Desktop e aguarde a indicação de que o mecanismo está ativo.","Execute os quatro comandos acima no PowerShell, sem acrescentar sudo.","Abra http://127.0.0.1:3000 no navegador. Se o Docker estiver em modo de containers Windows, altere para containers Linux."]),
 H("Linux — terminal",HeadingLevel.HEADING_2),...bullets(["Execute docker version. Se houver erro de conexão, inicie o serviço conforme a instalação da sua distribuição ou peça apoio ao professor.","Execute os quatro comandos acima. Use sudo somente se essa for a configuração institucional definida para o laboratório.","Abra http://127.0.0.1:3000 no navegador."]),
 callout("Pista","Se a porta 3000 já estiver ocupada, pare e confirme com o professor. Quando autorizado, use -p 127.0.0.1:3001:3000 e acesse http://127.0.0.1:3001.",C.cyan),
 H("Etapa 2 — Verificar o alvo e organizar a dupla (5 min)",HeadingLevel.HEADING_2),...bullets(["Confirme que a barra de endereço mostra exatamente 127.0.0.1 e a porta escolhida.","Registre o estado inicial sem capturar cookies, tokens ou credenciais.","Definam papéis: investigador opera; revisor confere escopo e anota. Troquem depois da observação.","Se a página não abrir, consulte docker logs --tail 30 juice-shop-a02. Não improvise contra outro endereço."]),
 callout("Evidência","Estado inicial: alvo sanitizado, horário relativo e confirmação de que a página inicial responde. Não capture credenciais, tokens, cookies ou IP público.",C.blue),
 H("Etapa 3 — Executar a requisição guiada (12 min)",HeadingLevel.HEADING_2),P("O professor executará a primeira vez com a turma. Abra DevTools, selecione Network, marque Preserve log e acesse exatamente http://127.0.0.1:3000/ftp/acquisitions.md. Não procure outras rotas."),
 Code("GET /ftp/acquisitions.md HTTP/1.1\nHost: 127.0.0.1:3000"),
 P("Localize a requisição e registre: método GET; caminho /ftp/acquisitions.md; status observado; Content-Type; presença ou ausência de autenticação; uma frase do documento que indique sua função ou sensibilidade. Não capture cookies ou tokens."),
 callout("Resultado esperado","Na imagem validada para a aula, a resposta é HTTP 200 e text/markdown. Se sua versão diferir, registre o resultado real e use a evidência impressa para continuar; não tente contornar o comportamento.",C.blue),
 callout("Pista","Um código 200 comprova que o servidor entregou o recurso naquela requisição. Ele não prova sozinho a causa, a autoria, o alcance nem a consequência.",C.cyan),
 H("Etapa 4 — Construir o inventário com apoio (8 min)",HeadingLevel.HEADING_2),P("Os ativos já estão nomeados para reduzir a carga inicial. Complete função, responsável provável e consequência usando apenas o ambiente investigado."),
 tbl(["Ativo fornecido","Função/responsável","Consequência","Evidência"],[["informação em acquisitions.md","","","trecho + resposta HTTP"],["arquivo acquisitions.md","","","caminho e tipo"],["rota/serviço web","","","GET e status"],["container Juice Shop","","","docker ps / URL local"]],[2400,2700,2700,2500]),
 H("Etapa 5 — Do observado aos conceitos (8 min)",HeadingLevel.HEADING_2),P("Use o exemplo iniciado pelo professor. Sua tarefa é justificar, limitar e corrigir as frases — não memorizar definições."),
 tbl(["Conceito","Ponto de partida","Justificativa ou limite da dupla"],[["Ativo","a informação e o arquivo têm valor para o cenário",""],["Ameaça","alguém sem autorização pode obter a informação",""],["Fraqueza — hipótese","arquivo em área servida ou autorização ausente",""],["Vulnerabilidade observada","esta implantação entrega o arquivo sem login",""],["Exposição/vetor","requisição HTTP GET para a rota fornecida",""],["Consequência","divulgação de planos fictícios de aquisição",""]],[2100,4300,3900]),
 callout("Distinção","Fraqueza explica uma condição provável e ainda exige arquitetura/configuração para confirmação. Vulnerabilidade, nesta atividade, é a instância concreta observada: a implantação entrega o recurso sem a restrição esperada.",C.cyan),
 callout("Decisão","Escolha uma prioridade pela consequência, não pela obtenção de uma flag. Explique o que mudaria a prioridade.",C.amber),
 H("Etapa 6 — Compreender, escolher e validar um controle (7 min)",HeadingLevel.HEADING_2),P("Controle é uma medida que modifica o risco: pode prevenir, detectar, corrigir ou apoiar recuperação. Uma ferramenta só se torna controle quando possui finalidade, responsável e forma de verificar seu funcionamento. Classifique as opções abaixo e recomende uma conforme a função do recurso."),
 tbl(["Opção","Melhor uso","Evidência/entrega","Limitação/risco"],[["Remover da área pública","recurso não deve ser servido","rota negada e publicação revisada","pode quebrar dependência"],["Autorizar no servidor","papel precisa acessar","casos permitido e negado","política incorreta"],["Reduzir conteúdo","publicação é necessária","somente dados necessários","não corrige outras rotas"],["Detectar acessos","correção não imediata","log/alerta testado","não impede exposição"]],[1900,2600,2900,2900]),
 P("Controle escolhido e premissa: __________________________________________________"),P("Reteste e resultado esperado: ___________________________________________________"),
 H("Entrega"),P("Envie no Google Classroom um PDF chamado A02-dupla-NN.pdf com: hipótese inicial; inventário priorizado; uma evidência interpretada; registro de vulnerabilidade; controle e reteste; reflexão de até cinco linhas. Uma captura sem interpretação não conta como evidência."),
 H("Critérios de sucesso"),tbl(["Critério","Atendeu","Parcial"],[["Inventário","ativos, função, proprietário e consequência","lista sem priorização"],["Precisão","termos distintos e limites explícitos","mistura termos ou afirma causa"],["Evidência","reproduzível, sanitizada e interpretada","captura pouco explicada"],["Tratamento","controle ligado à causa e reteste","controle genérico"],["Conduta","escopo e parada respeitados","registro incompleto"]],[2300,4000,4000]),
 new Paragraph({children:[new PageBreak()]}),H("Limpeza e encerramento"),P("Windows PowerShell e Linux usam o mesmo comando para parar o container:"),Code("docker stop juice-shop-a02"),...bullets(["Confirme que docker ps --filter name=juice-shop-a02 não lista o container em execução.","Como foi usado --rm, o container é removido automaticamente após a parada; a imagem permanece para reutilização.","Feche DevTools e descarte capturas que contenham cookies, tokens ou dados não sanitizados.","Confirme que http://127.0.0.1:3000 não responde mais e preserve somente o PDF sanitizado."]),
 H("Extensão opcional"),P("Proponha uma consulta de inventário que encontraria exposições semelhantes sem varrer redes ou testar terceiros. Indique fonte dos dados, responsável e critério de atualização."),
 H("Transferência"),P("Em uma HMI industrial, qual consequência física e qual janela de manutenção mudariam a escolha entre remover, autorizar e monitorar?"),
 H("Fontes oficiais"),...bullets(["OWASP Juice Shop — execução com Docker: https://pwning.owasp-juice.shop/companion-guide/latest/part1/running.html","Docker Desktop para Windows: https://docs.docker.com/desktop/setup/install/windows-install/","Docker Engine para Linux: https://docs.docker.com/engine/install/","NIST CSF 2.0 — https://doi.org/10.6028/NIST.CSWP.29","CVE Program — https://www.cve.org/","CWE — https://cwe.mitre.org/"])
]}]});
await writeFile(resolve(activityRoot,"fonte","A02-ativos-ameacas-e-vulnerabilidades.docx"),await Packer.toBuffer(doc));
