import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const pptxgen = require("pptxgenjs");
import { AlignmentType, Document, Footer, HeadingLevel, Packer, PageBreak, Paragraph, ShadingType, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
const slug = "A02-ativos-ameacas-e-vulnerabilidades";
const slideRoot = resolve(root, "slides", slug);
const activityRoot = resolve(root, "atividades", slug);
await Promise.all([
  mkdir(resolve(slideRoot, "fonte"), { recursive: true }), mkdir(resolve(slideRoot, "assets"), { recursive: true }), mkdir(resolve(slideRoot, "exportados"), { recursive: true }),
  mkdir(resolve(activityRoot, "fonte"), { recursive: true }), mkdir(resolve(activityRoot, "assets"), { recursive: true }), mkdir(resolve(activityRoot, "pdf"), { recursive: true }),
]);

const C={navy:"12304A",blue:"0B65C2",cyan:"087F7A",amber:"B75D00",red:"B42318",paper:"F4F7FA",ink:"172B4D",white:"FFFFFF",grey:"4B5E71",line:"C9D4DF",pale:"E7F0F8",green:"26734D"};
const pptx=new pptxgen(); pptx.layout="LAYOUT_WIDE"; pptx.author="Curso de Segurança Digital"; pptx.title="A02 — Ativos, ameaças e vulnerabilidades"; pptx.lang="pt-BR"; pptx.theme={headFontFace:"Arial",bodyFontFace:"Arial",lang:"pt-BR"};
const notes=(s,t)=>s.addNotes(t);
const footer=(s,src="NIST CSF 2.0 • CWE • CVE")=>{s.addShape(pptx.ShapeType.line,{x:.6,y:7.08,w:12.05,h:0,line:{color:C.line,width:1}});s.addText("A02  •  Segurança Digital",{x:.65,y:7.14,w:4,h:.2,fontSize:10,color:C.grey,margin:0});s.addText(src,{x:6.5,y:7.14,w:6.15,h:.2,fontSize:9,color:C.grey,align:"right",margin:0});};
const head=(s,k,t,sub="")=>{s.addText(k.toUpperCase(),{x:.7,y:.42,w:4.8,h:.28,fontSize:13,bold:true,color:C.cyan,charSpacing:1,margin:0});s.addText(t,{x:.7,y:.84,w:11.9,h:.72,fontSize:30,bold:true,color:C.navy,margin:0,fit:"shrink"});if(sub)s.addText(sub,{x:.72,y:1.65,w:11.4,h:.44,fontSize:17,color:C.grey,margin:0,fit:"shrink"});};
const card=(s,x,y,w,h,title,body,color=C.blue)=>{s.addShape(pptx.ShapeType.roundRect,{x,y,w,h,fill:{color:C.white},line:{color,width:2}});s.addText(title,{x:x+.22,y:y+.25,w:w-.44,h:.3,fontSize:14,bold:true,color,margin:0});s.addText(body,{x:x+.22,y:y+.82,w:w-.44,h:h-1.05,fontSize:18,bold:true,color:C.ink,margin:0,fit:"shrink",valign:"mid"});};

{
 const s=pptx.addSlide();s.background={color:C.navy};s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:.22,h:7.5,fill:{color:C.cyan},line:{color:C.cyan}});s.addText("A02  •  FUNDAMENTOS E RISCO",{x:.8,y:.72,w:5.5,h:.32,fontSize:14,bold:true,color:"7DE0D8",charSpacing:1.2,margin:0});s.addText("O que realmente\nestá exposto?",{x:.8,y:1.45,w:7.1,h:1.55,fontSize:40,bold:true,color:C.white,margin:0});s.addText("O servidor entregou um arquivo interno. Qual ativo, fraqueza e consequência justificam agir primeiro?",{x:.82,y:3.35,w:7.3,h:1.1,fontSize:21,color:"E6EEF5",margin:0,fit:"shrink"});s.addShape(pptx.ShapeType.roundRect,{x:9.05,y:1.45,w:3.25,h:3.15,fill:{color:"071720"},line:{color:"7DE0D8",width:2}});s.addText("HTTP/1.1\n200 OK",{x:9.38,y:2.18,w:2.6,h:1.15,fontFace:"Courier New",fontSize:27,bold:true,color:C.white,align:"center",valign:"mid",margin:0});s.addText("2 × 52 min  •  investigação em duplas",{x:.82,y:6.55,w:5.2,h:.3,fontSize:14,color:"C7D6E4",margin:0});notes(s,"Mostre a resposta por 30 segundos. Colete observações sem aceitar ainda as palavras vulnerabilidade ou ataque como fatos.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Missão","Transformar uma exposição em decisão verificável","Você integra a equipe que revisa a publicação da loja de testes.");card(s,.75,2.35,3.72,2.7,"RESTRIÇÃO","Somente o Juice Shop local fornecido.",C.red);card(s,4.8,2.35,3.72,2.7,"INVESTIGAÇÃO","Uma requisição por vez; sem enumeração.",C.amber);card(s,8.85,2.35,3.72,2.7,"ENTREGA","Inventário + registro + reteste.",C.cyan);footer(s);notes(s,"Confirme alvo, dados fictícios e critério de parada. DevTools é suficiente; Burp é opcional.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Previsão","O que o código 200 permite afirmar?","Registre antes de conhecer a arquitetura.");s.addShape(pptx.ShapeType.roundRect,{x:.8,y:2.2,w:7.2,h:3.55,fill:{color:"0D2235"},line:{color:"31556D"}});s.addText("GET /ftp/acquisitions.md\n\nHTTP/1.1 200 OK\nContent-Type: text/markdown",{x:1.25,y:2.75,w:6.3,h:2.2,fontFace:"Courier New",fontSize:20,color:"D8F3EA",margin:0});s.addText("REGISTRE",{x:8.85,y:2.4,w:2.5,h:.3,fontSize:14,bold:true,color:C.blue,margin:0});s.addText("2 observações\n1 ativo\n1 hipótese\n1 lacuna",{x:8.85,y:3,w:3,h:1.8,fontSize:22,bold:true,color:C.navy,margin:0});footer(s,"Evidência fictícia preparada para a disciplina");notes(s,"Resposta esperada: o recurso foi entregue naquela requisição. Não há prova suficiente de autoria, intenção, alcance ou causa.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Ativos","Inventário começa pela consequência","Um item sem função e proprietário conhecidos não pode ser priorizado com confiança.");const data=[["ATIVO","FUNÇÃO","CONSEQUÊNCIA"],["Catálogo/API","vender e consultar","fraude ou parada"],["Dados fictícios","sustentar pedidos","exposição e confiança"],["Container","executar a loja","ampliação ou indisponibilidade"],["Controlador OT","comandar processo","produção e safety"]];s.addTable(data.map(r=>r.map(text=>({text}))),{x:.75,y:2.2,w:11.85,h:3.45,border:{color:C.line,width:1},fill:C.white,color:C.ink,fontSize:16,margin:.12,rowH:.67,bold:false,valign:"mid",autoFit:false});s.addText("ID.AM: inventariar, manter e priorizar ativos conforme missão e impacto.",{x:1,y:5.95,w:11.2,h:.45,fontSize:19,bold:true,color:C.navy,align:"center",margin:0});footer(s,"NIST Cybersecurity Framework 2.0 — ID.AM");notes(s,"Peça um ativo que não seja equipamento. Em OT, acrescente processo físico, qualidade, ambiente e safety.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Conceitos","Uma cadeia, seis perguntas","Os termos ganham precisão quando ligados à mesma evidência.");const items=[["ATIVO","o que tem valor?",C.blue],["AMEAÇA","quem ou o que causa dano?",C.red],["FRAQUEZA","que condição pode originar falhas?",C.amber],["VULNERABILIDADE","qual instância é explorável?",C.cyan],["EXPOSIÇÃO","por qual caminho é alcançável?",C.green],["EXPLOIT","que técnica usa a falha?",C.navy]];items.forEach(([h,b,c],i)=>{const col=i%3,row=Math.floor(i/3),x=.65+col*4.22,y=2.18+row*1.75;card(s,x,y,3.85,1.42,h,b,c);});footer(s,"CWE — glossary and FAQ; CVE Program");notes(s,"CWE é classe de fraqueza; CVE é vulnerabilidade específica publicada. Não atribuir CVE ao desafio sem fonte.");
}
{
 const s=pptx.addSlide();s.background={color:C.navy};s.addText("CHECKPOINT 2",{x:.8,y:.7,w:4,h:.3,fontSize:14,bold:true,color:"7DE0D8",charSpacing:1.2,margin:0});s.addText("Qual controle você defenderia?",{x:.8,y:1.45,w:10.8,h:.9,fontSize:38,bold:true,color:C.white,margin:0});const opts=[["REMOVER","recurso não deveria ser servido"],["AUTORIZAR","papel específico precisa acessar"],["MONITORAR","correção imediata é inviável"]];opts.forEach(([h,b],i)=>{const x=.8+i*4.05;s.addShape(pptx.ShapeType.roundRect,{x,y:3,w:3.55,h:2,fill:{color:["174C76","12635F","70461B"][i]},line:{color:C.white,width:1}});s.addText(h,{x:x+.25,y:3.35,w:3.05,h:.35,fontSize:17,bold:true,color:C.white,align:"center",margin:0});s.addText(b,{x:x+.3,y:4,w:2.95,h:.62,fontSize:17,color:C.white,align:"center",margin:0});});s.addText("Declare a premissa e a evidência de reteste.",{x:.9,y:6.35,w:11.3,h:.4,fontSize:18,color:"D6E5F0",align:"center",margin:0});notes(s,"Monitorar não substitui correção. Aceite escolhas condicionadas à função do arquivo e à arquitetura.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Demonstração","Preveja antes de abrir a rota","A exploração termina em tratamento e validação.");const steps=[["1","CONFIRMAR","alvo e estado"],["2","PREVER","recurso e resposta"],["3","OBSERVAR","requisição única"],["4","REGISTRAR","causa e impacto"],["5","VALIDAR","controle e reteste"]];steps.forEach(([n,h,b],i)=>{const x=.43+i*2.58;s.addShape(pptx.ShapeType.roundRect,{x,y:2.45,w:2.3,h:2.55,fill:{color:C.white},line:{color:i===4?C.green:C.line,width:i===4?2:1}});s.addText(n,{x:x+.78,y:2.7,w:.72,h:.55,fontSize:22,bold:true,color:C.white,fill:{color:i===4?C.green:C.blue},align:"center",margin:0});s.addText(h,{x:x+.15,y:3.48,w:2,h:.32,fontSize:14,bold:true,color:C.navy,align:"center",margin:0});s.addText(b,{x:x+.18,y:4.05,w:1.94,h:.55,fontSize:16,color:C.ink,align:"center",margin:0});});footer(s,"OWASP Juice Shop — ambiente local autorizado");notes(s,"Plano alternativo: use a resposta HTTP e os ativos do PDF. Não improvise contra a demonstração pública.");
}
{
 const s=pptx.addSlide();s.background={color:C.white};head(s,"Prática","Produza um ticket que outra equipe possa retestar","A flag não é o produto da atividade.");s.addShape(pptx.ShapeType.roundRect,{x:.8,y:2.2,w:7.55,h:3.65,fill:{color:"E7F5F3"},line:{color:C.cyan,width:2}});s.addText("MISSÃO",{x:1.2,y:2.65,w:2,h:.3,fontSize:15,bold:true,color:C.cyan,margin:0});s.addText("Relacione ativo, fraqueza, vetor e impacto; escolha um controle e prove como validá-lo.",{x:1.2,y:3.25,w:6.3,h:1.5,fontSize:25,bold:true,color:C.navy,margin:0,fit:"shrink"});s.addText("ENTREGA",{x:9.1,y:2.55,w:2.6,h:.3,fontSize:15,bold:true,color:C.blue,margin:0});s.addText("Inventário priorizado\nEvidência interpretada\nControle justificado\nReteste definido",{x:9.1,y:3.1,w:3.1,h:1.75,fontSize:19,bold:true,color:C.navy,margin:0});s.addText("Sem credenciais ou dados reais",{x:9.1,y:5.25,w:3.1,h:.5,fontSize:14,color:C.red,margin:0});footer(s);notes(s,"Distribua o PDF e troque os papéis após a evidência inicial.");
}
{
 const s=pptx.addSlide();s.background={color:C.paper};head(s,"Síntese","Inventário orienta a prioridade","A terminologia conecta evidência, causa, consequência, ação e validação.");const chain=[["INVENTARIAR",C.blue],["OBSERVAR",C.cyan],["EXPLICAR",C.amber],["TRATAR",C.red],["RETESTAR",C.green]];chain.forEach(([t,c],i)=>{const x=.45+i*2.58;s.addShape(pptx.ShapeType.roundRect,{x,y:2.65,w:2.3,h:1.2,fill:{color:c},line:{color:c}});s.addText(t,{x:x+.12,y:3.03,w:2.06,h:.35,fontSize:15,bold:true,color:C.white,align:"center",margin:0});});s.addText("Transferência: qual consequência física mudaria sua prioridade em uma HMI?",{x:1.05,y:4.8,w:11.2,h:.9,fontSize:24,bold:true,color:C.navy,align:"center",margin:0});footer(s,"NIST CSF 2.0; CWE; CVE; OWASP Juice Shop");notes(s,"Feche com: Priorizamos o ativo..., porque..., e validaremos o controle por...");
}
await pptx.writeFile({fileName:resolve(slideRoot,"fonte","A02-ativos-ameacas-e-vulnerabilidades.pptx")});

const H=(text,level=HeadingLevel.HEADING_1)=>new Paragraph({text,heading:level,spacing:{before:220,after:100},keepNext:true});
const P=(text,opts={})=>new Paragraph({children:[new TextRun({text,size:24,color:C.ink})],spacing:{after:120,line:330},...opts});
const Cell=(text,fill="FFFFFF",bold=false,color=C.ink,width=null)=>new TableCell({width:width?{size:width,type:WidthType.DXA}:undefined,shading:{type:ShadingType.CLEAR,fill},margins:{top:120,bottom:120,left:150,right:150},children:[new Paragraph({children:[new TextRun({text,bold,color,size:22})],spacing:{after:0,line:290}})]});
const callout=(label,text,color)=>new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[new TableCell({shading:{type:ShadingType.CLEAR,fill:color},margins:{top:145,bottom:145,left:180,right:180},children:[new Paragraph({children:[new TextRun({text:label.toUpperCase(),bold:true,color:"FFFFFF",size:23})],spacing:{after:65}}),new Paragraph({children:[new TextRun({text,color:"FFFFFF",size:23})],spacing:{line:315}})]})]})]});
const bullets=(items)=>items.map(text=>new Paragraph({children:[new TextRun({text,size:24,color:C.ink})],bullet:{level:0},spacing:{after:85,line:315}}));
const tbl=(headers,rows,widths)=>new Table({width:{size:10300,type:WidthType.DXA},columnWidths:widths,rows:[new TableRow({tableHeader:true,children:headers.map((x,i)=>Cell(x,C.navy,true,"FFFFFF",widths[i]))}),...rows.map(r=>new TableRow({children:r.map((x,i)=>Cell(x,"FFFFFF",false,C.ink,widths[i]))}))]});
const doc=new Document({creator:"Curso de Segurança Digital",title:"A02 — Ativos, ameaças e vulnerabilidades — prática",styles:{default:{document:{run:{font:"Arial",size:24,color:C.ink},paragraph:{spacing:{line:330}}}},paragraphStyles:[{id:"Title",name:"Title",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Arial",size:42,bold:true,color:C.navy},paragraph:{spacing:{after:180}}},{id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Arial",size:31,bold:true,color:C.navy},paragraph:{spacing:{before:240,after:100},outlineLevel:0}},{id:"Heading2",name:"Heading 2",basedOn:"Normal",next:"Normal",quickFormat:true,run:{font:"Arial",size:27,bold:true,color:C.blue},paragraph:{spacing:{before:180,after:80},outlineLevel:1}}]},sections:[{properties:{page:{margin:{top:800,right:800,bottom:800,left:800}}},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:"A02 • Segurança Digital • roteiro do estudante",font:"Arial",size:18,color:C.grey})]})]})},children:[
 new Paragraph({children:[new TextRun({text:"A02 • FUNDAMENTOS E RISCO",bold:true,color:C.cyan,size:23})],spacing:{after:120}}),new Paragraph({text:"O que realmente está exposto?",style:"Title"}),P("Missão: investigar uma exposição simples no Juice Shop local e produzir um registro que conecte ativo, fraqueza, vetor, consequência, controle e reteste."),
 tbl(["Duração","Organização","Entrega"],[["52 minutos","duplas; papéis rotativos","um PDF por dupla"]],[3400,3400,3500]),
 H("Objetivos"),...bullets(["Inventariar ativos de TI e OT relacionando função e consequência.","Distinguir ameaça, fraqueza, vulnerabilidade, exposição e exploit na evidência.","Priorizar o registro, escolher controle e definir validação reproduzível."]),
 H("Pré-requisitos e recursos"),...bullets(["A01 e página MkDocs A02 consultável durante a atividade.","Juice Shop local no endereço informado pelo professor.","Navegador com DevTools; Burp Community é opcional.","Este roteiro contém evidência alternativa para falha do ambiente."]),
 callout("Atenção","Escopo: somente o Juice Shop local fornecido. Não teste a demonstração pública, sistemas institucionais ou terceiros. Use dados fictícios. Pare se o destino divergir, houver dados reais ou o comportamento alcançar outro sistema.",C.red),
 H("Hipótese inicial"),P("Antes de executar, registre qual recurso pode estar exposto, por que isso seria possível e qual resposta confirmaria ou refutaria sua hipótese."),P("Hipótese: __________________________________________________________________"),P("Evidência esperada: __________________________________________________________"),
 new Paragraph({children:[new PageBreak()]}),H("Etapa 1 — Preparar e verificar (8 min)",HeadingLevel.HEADING_2),...bullets(["Copie do quadro o endereço exato do alvo local; confirme protocolo, host e porta.","Abra a página inicial e registre somente versão/identificação exibida sem dados sensíveis.","Definam papéis: investigador opera; revisor confere escopo e anota. Troquem depois da Etapa 2.","Se a página não abrir ou o destino não for o indicado, use a evidência alternativa e não improvise."]),
 callout("Evidência","Estado inicial: alvo sanitizado, horário relativo e confirmação de que a página inicial responde. Não capture credenciais, tokens, cookies ou IP público.",C.blue),
 H("Etapa 2 — Observar sem enumerar (12 min)",HeadingLevel.HEADING_2),P("Com DevTools na aba Network, observe uma requisição orientada pelo professor. Execute uma tentativa por vez. Registre método, caminho relativo, status, tipo de conteúdo e o que a resposta demonstra. Não use scanner, força bruta ou lista de caminhos."),
 callout("Alternativa","Se o ambiente falhar, use: GET /ftp/acquisitions.md → HTTP/1.1 200 OK, Content-Type: text/markdown. Trate-a como evidência fictícia; não presuma conteúdo que não foi mostrado.",C.blue),
 callout("Pista","Um código 200 comprova que o servidor entregou o recurso naquela requisição. Ele não prova sozinho a causa, a autoria, o alcance nem a consequência.",C.cyan),
 H("Etapa 3 — Inventariar e interpretar (12 min)",HeadingLevel.HEADING_2),P("Preencha ao menos quatro linhas. Inclua o recurso observado, a aplicação, a plataforma e um ativo OT de transferência."),
 tbl(["Ativo/tipo","Função/proprietário","Consequência","Prioridade e evidência"],[["","","",""],["","","",""],["","","",""],["","","",""]],[2200,2700,2800,2600]),
 H("Etapa 4 — Registrar a vulnerabilidade (10 min)",HeadingLevel.HEADING_2),P("Descreva comportamento esperado e observado. Relacione: ativo; ameaça plausível; fraqueza provável; vulnerabilidade concreta; caminho de exposição; técnica necessária; consequência; limites da hipótese. Não invente um CVE."),
 tbl(["Campo","Registro da dupla"],[["Evidência reproduzível e interpretação",""],["Fraqueza provável e lacuna",""],["Vetor/ameaça dentro do escopo",""],["Consequência e prioridade",""],["Limites e próxima evidência",""]],[3300,7000]),
 callout("Decisão","Escolha uma prioridade pela consequência, não pela obtenção de uma flag. Explique o que mudaria a prioridade.",C.amber),
 H("Etapa 5 — Tratar e validar (10 min)",HeadingLevel.HEADING_2),P("Compare as opções e recomende uma conforme a função do recurso."),
 tbl(["Opção","Melhor uso","Evidência/entrega","Limitação/risco"],[["Remover da área pública","recurso não deve ser servido","rota negada e publicação revisada","pode quebrar dependência"],["Autorizar no servidor","papel precisa acessar","casos permitido e negado","política incorreta"],["Reduzir conteúdo","publicação é necessária","somente dados necessários","não corrige outras rotas"],["Detectar acessos","correção não imediata","log/alerta testado","não impede exposição"]],[1900,2600,2900,2900]),
 P("Controle escolhido e premissa: __________________________________________________"),P("Reteste e resultado esperado: ___________________________________________________"),
 H("Entrega"),P("Envie no Google Classroom um PDF chamado A02-dupla-NN.pdf com: hipótese inicial; inventário priorizado; uma evidência interpretada; registro de vulnerabilidade; controle e reteste; reflexão de até cinco linhas. Uma captura sem interpretação não conta como evidência."),
 H("Critérios de sucesso"),tbl(["Critério","Atendeu","Parcial"],[["Inventário","ativos, função, proprietário e consequência","lista sem priorização"],["Precisão","termos distintos e limites explícitos","mistura termos ou afirma causa"],["Evidência","reproduzível, sanitizada e interpretada","captura pouco explicada"],["Tratamento","controle ligado à causa e reteste","controle genérico"],["Conduta","escopo e parada respeitados","registro incompleto"]],[2300,4000,4000]),
 new Paragraph({children:[new PageBreak()]}),H("Limpeza e encerramento"),...bullets(["Feche DevTools e descarte capturas que contenham cookies, tokens ou dados não sanitizados.","Se você iniciou o Juice Shop, encerre o processo ou container pelo procedimento informado.","Confirme que a porta do serviço vulnerável não ficou acessível fora do laboratório.","Preserve somente o PDF sanitizado da entrega."]),
 H("Extensão opcional"),P("Proponha uma consulta de inventário que encontraria exposições semelhantes sem varrer redes ou testar terceiros. Indique fonte dos dados, responsável e critério de atualização."),
 H("Transferência"),P("Em uma HMI industrial, qual consequência física e qual janela de manutenção mudariam a escolha entre remover, autorizar e monitorar?"),
 H("Fontes oficiais"),...bullets(["NIST CSF 2.0 — https://doi.org/10.6028/NIST.CSWP.29","CVE Program — https://www.cve.org/","CWE — https://cwe.mitre.org/","OWASP Juice Shop — https://owasp.org/www-project-juice-shop/"])
]}]});
await writeFile(resolve(activityRoot,"fonte","A02-ativos-ameacas-e-vulnerabilidades.docx"),await Packer.toBuffer(doc));
