site_name: Segurança Digital 
site_author: Prof. Rafael Emerick
theme: material

nav:
  - Fundamentos de Segurança:
      - Visão geral: fundamentos_de_seguranca_digital/index.md
      - Ameaças e Vulnerabilidades: fundamentos_de_seguranca_digital/B-ameacas_vulnerabilidades.md
      - Confidencialidade: fundamentos_de_seguranca_digital/C-confidencialidade.md
      - Integridade: fundamentos_de_seguranca_digital/D-integridade.md
      - Disponibilidade: fundamentos_de_seguranca_digital/E-disponibilidade.md
      - Não Repudio: fundamentos_de_seguranca_digital/F-nao-repudio.md
      - Autorização: fundamentos_de_seguranca_digital/H-autorizacao.md
      - Accounting: fundamentos_de_seguranca_digital/I-accounting.md
      - Controles de Segurança: fundamentos_de_seguranca_digital/J-Controles_seguranca.md
      - Zero Trust: fundamentos_de_seguranca_digital/K-zerotrust.md
      - Análise de Gaps: fundamentos_de_seguranca_digital/L-analise-lacunas.md
  - Ameaças :
      - Visão geral: ameacas/index.md
      - Metodologias de análise de ameaças: ameacas/metodologias.md
      - Compartivo de metodologias: ameacas/comparativo.md
  - Segurança Física:
      - Introdução: seguranca_fisica/introducao.md
      - Controles de Segurança Física: seguranca_fisica/controles_fisicos.md
      - Força Bruta: seguranca_fisica/forca_bruta.md
      - Sistemas de Vigilância: seguranca_fisica/sistema_vigilancia.md
      - Bypass da Vigilância: seguranca_fisica/bypass_vigilancia.md
      - Câmaras de acesso controlado: seguranca_fisica/camaras_acesso.md
      - Fechaduras e Trancas: seguranca_fisica/fechaduras_trancas.md
      - Clonagem de acesso: segurança_fisica/clonagem_cracha.md
  - Engenharia Social:
      - Introdução: engenharia_social/introducao.md
      - Gatilhos Motivacionais: engenharia_social/gatilhos.md
      - Impersonificação: engenharia_social/impersonificacao.md
      - Falsificação de pretextos: engenharia_social/pretexting.md
      - Ataques de phishing: engenharia_social/pishing.md
      - Prevenção de Phishing: engenharia_social/prevencao_phishing.md
      - Campanha Simulação de Phishing: engenharia_social/campanhas_simulacao_pishing.md
      - Fraudes e Golpes(Scams): engenharia_social/fraudes_golpes.md
      - Campanhas de Influência e Desinformação: engenharia_social/desinformacao.md
      - Outros Ataques: engenharia_social/outros_ataques.md
  - Malwares:
      - Introdução: malwares/introducao.md
      - Virus: malwares/virus.md
      - Worms: malwares/worms.md
      - Trojans: malwares/trojans.md
      - Ransomware: malwares/ransomware.md
      - Botnets: malwares/botnet.md
      - Rootkits: malwares/rootkit.md
      - Backdoors: malwares/backdoors.md
      - Keylogger: malwares/keylogger.md
      - Spywares: malwares/spyware.md
      - Técnicas de Ataque: malwares/tecnica_ataque.md
  - Proteção de dados:
      - Introdução: protecao_dados/introducao.md
      - Classificação de dados: protecao_dados/classificacao_dados.md
      - Propriedade de dados: protecao_dados/propriedade_dados.md
      - Estado de dados: protecao_dados/estado_dados.md
      - Tipos de dados: protecao_dados/tipos_dados.md
      - Soberania de dados: protecao_dados/soberania_dados.md
      - Métodos de proteção de dados: protecao_dados/metodos_protecao.md
      - Prevenção de perda de dados: protecao_dados/prevencao_perda.md
      - Configuração de DLP: protecao_dados/configuracao_dlp.md
  - Criptografia:
      - Introdução: criptografia/index.md
      - Tipos de Criptografia: criptografia/principais_tipos.md
      - Algorítmos Simétricos: criptografia/simetricos.md
      - Algorítmos Assimétricos: criptografia/assimetricos.md]
      - Hashing: criptografia/hash.md
      - Segurança de Hashes: criptografia/seguranca_de_hashes.md
      - PKI: criptografia/pki.md
      - Certificados Digitais: criptografia/certificados_digitais.md
      - Exemplos de Certificado: criptografia/exemplo_certificado.md
      - Blockchain: criptografia/blockchain.md
      - Ferramentas: criptografia/ferramentas.md
      - Ofuscação: criptografia/ofuscacao.md
      - Ameaças à Criptografia: criptografia/ameacas_criptografia.md
